<script src="../assets/js/jquery.js"></script> 
<script src="../assets/js/validate.js"></script>
<script src="../assets/js/bootstrap.min.js"></script>
<script src="../assets/js/revolution.min.js"></script>
<script src="../assets/js/rev-slider.js"></script>
<script src="../assets/js/owl.js"></script>
<script src="../assets/js/isotope.js"></script>
<script src="../assets/js/jquery.mixitup.min.js"></script>
<script src="../assets/js/jquery.prettyPhoto.js"></script>
<script src="../assets/js/jquery.appear.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="../assets/js/googlemaps.js"></script>
<script src="../assets/js/script.js"></script>
